sonarqube:
  image:
    repository: sonarqube
    tag: 9.9.4-community
  port: 9000
  storage:
    data: 20Gi
    extensions: 2Gi
    logs: 1Gi
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000

service:
  type: LoadBalancer
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

postgres:
  image: postgres:15
  user: sonar
  password: sonarpass
  database: sonarqube
  port: 5432
  storage: 5Gi

ingress:
  enabled: true
  hostname: sonarqube.local
  className: nginx
