apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-backup-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gitlab-backup
  hostPath:
    path: /mnt/data/gitlab-backups
