apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-new
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3-csi
