apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-new
  labels:
    app: postgres
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3-csi
  hostPath:
    path: /mnt/postgres-data
