apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-pv-new
  labels:
    app: vault
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3-csi
  hostPath:
    path: /mnt/vault-data
