apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-pvc-new
  labels:
    app: vault
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3-csi
