apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-agent-injector
  namespace: vault  # Use a custom namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vault-agent-injector
      app.kubernetes.io/instance: vault
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault-agent-injector
        app.kubernetes.io/instance: vault
      annotations:
        vault.hashicorp.com/agent-inject: "true"
    spec:
      serviceAccountName: vault-agent-injector
      containers:
        - name: vault-agent-injector
          image: hashicorp/vault-k8s:1.0.0
          args:
            - agent-inject
            - -log-level=debug
          env:
            - name: AGENT_INJECT_IMAGE
              value: "hashicorp/vault:1.15.0"
            - name: AGENT_INJECT_VAULT_ADDR
              value: "http://vault:8200"
            - name: AGENT_INJECT_VAULT_AUTH_PATH
              value: "auth/kubernetes"
            - name: AGENT_INJECT_VAULT_ROLE
              value: "vault-agent-injector"
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
            requests:
              cpu: "250m"
              memory: "64Mi"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - NET_RAW  # Drop unnecessary capabilities
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-agent-injector
  labels:
    app.kubernetes.io/name: vault-agent-injector
    app.kubernetes.io/instance: vault
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "patch"]
