apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: {{ .Values.vault.replicas }}
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: {{ .Values.vault.image }}
        ports:
        - containerPort: 8200
        volumeMounts:
        - name: vault-storage
          mountPath: {{ .Values.vault.storagePath }}
      volumes:
      - name: vault-storage
        persistentVolumeClaim:
          claimName: vault-pvc-new
