apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  annotations:
    {{- with .Values.service.annotations }}
    {{ toYaml . | indent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: sonarqube
  ports:
    - port: {{ .Values.sonarqube.port }}
      targetPort: {{ .Values.sonarqube.port }}
