apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-extensions-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/sonarqube/extensions
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
