apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-logs-pv
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: sonarqube-1
    meta.helm.sh/release-namespace: sonarqube
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/sonarqube/logs
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
